name: 'GCS Cache'
author: 'vietanhduong'
description: 'Cache your workload to a Google Cloud Storage bucket'

inputs:
  bucket:
    description: Name of the bucket to store the cache into
    required: true
  path:
    description: Paths to store
    required: true
  key:
    description: Key to use as cache identifier
    required: true
  restore-keys:
    description: Substitution keys to use when cache miss
    default: ''
    required: false
  compression-method:
    description: Compression method for the archive (gzip, zstd, lz4)
    default: ''
    required: false
  key-file-name:
    description: GCS auth key file path
    default: ''
    required: false

outputs:
  cache-hit:
    description: Whether the cache was successfuly restored

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: 'success()'

branding:
  icon: 'hard-drive'
  color: 'blue'
